# Generated by Django 5.2.17 on 2026-08-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_staff'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('sample_required', models.CharField(max_length=100)),
                ('normal_range', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('lab_prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_bill', to='doctor.labprescription')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('lab_prescription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_result', to='doctor.labprescription')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='accounts.staff')),
            ],
        ),
    ]
