# Generated by Django 5.2.17 on 2026-09-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresult',
            old_name='tested_at',
            new_name='report_date',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='result',
            new_name='result_value',
        ),
        migrations.RemoveField(
            model_name='labbill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='id',
        ),
        migrations.AddField(
            model_name='labbill',
            name='lab_bill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='labbill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_bills', to='receptionist.patient'),
        ),
        migrations.AddField(
            model_name='labbill',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='emailed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='result_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
