# Generated by Django 5.2.17 on 2026-09-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_rename_tested_at_labresult_report_date_and_more'),
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_bills', to='receptionist.patient'),
        ),
    ]
