# Generated by Django 5.2.17 on 2026-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_labbill_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbill',
            name='emailed_status',
            field=models.BooleanField(default=False),
        ),
    ]
