# Generated by Django 5.2.17 on 2026-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_create_pharmacist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinebill',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
