# Generated by Django 5.2.17 on 2026-09-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=150, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('sample_required', models.CharField(max_length=150)),
                ('normal_range', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='accounts.department')),
            ],
            options={
                'db_table': 'lab_tests',
            },
        ),
    ]
