# Generated by Django 5.2.17 on 2026-09-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_labtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTest',
        ),
    ]
