# Generated by Django 5.2.17 on 2026-08-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('dispensed_status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('consultation_date', models.DateField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receptionist.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='LabPrescription',
            fields=[
                ('lab_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_prescriptions', to='doctor.consultation')),
            ],
        ),
    ]
