# Generated by Django 5.2.17 on 2026-08-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescription',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtest'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine'),
        ),
    ]
