# Generated by Django 5.2.17 on 2026-09-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_medicineprescription_quantity'),
        ('pharmacy', '0003_create_pharmacist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='other_medicine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='other_medicine_type',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='dispensed_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('OUTSIDE', 'Purchase Outside')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medicine'),
        ),
    ]
