# Generated by Django 5.2.17 on 2026-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('WALK_IN', 'Walk-in'), ('PRIOR_BOOKING', 'Prior Booking')], default='WALK_IN', max_length=20),
        ),
    ]
