# Generated by Django 5.2.17 on 2026-09-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff'),
        ('receptionist', '0002_appointment_appointment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('morning_break_start', models.TimeField(blank=True, null=True)),
                ('morning_break_end', models.TimeField(blank=True, null=True)),
                ('afternoon_break_start', models.TimeField(blank=True, null=True)),
                ('afternoon_break_end', models.TimeField(blank=True, null=True)),
                ('evening_break_start', models.TimeField(blank=True, null=True)),
                ('evening_break_end', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.PositiveIntegerField(default=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='accounts.staff')),
            ],
            options={
                'unique_together': {('doctor', 'weekday')},
            },
        ),
    ]
